import Navbar_component from "../components/Navbar_component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar_component></Navbar_component>
        {children}</body>
    </html>
  );
}
